### PR TITLE
fix: issue #20 - supporting access to value via descriptor

### LINKED ISSUE #20: getOwnPropertyDescriptor() can be used to get access to raw values
### Description
When an observable value has a configurable property, the reactive proxy and the readonly proxy can be bypassed to gain access to the underlying raw value.
 
This can be done using the getOwnPropertyDescriptor() to gain access to the raw descriptor of the raw value. In the case of the read-only proxy, the user can bypass the read only membrane and mutate the original object.

Further, the proxy implementation has to protection for descriptors that have a getter/setter.

#### Steps to Reproduce
```
const target = new ReactiveMembrane();
const todos = {};
const observable = {};
Object.defineProperty(todos, 'foo', {
    get() {
        return observable;
    },
    configurable: true
});

const proxy = target.getProxy(todos);
const desc = Object.getOwnPropertyDescriptor(proxy, 'foo');
const { get } = desc;
get(); // Will return the raw observable object. expected to see a reactive proxy
proxy.foo; // Will return a reactive proxy as expected
```
```
const target = new ReactiveMembrane();
const todos = {};
const observable = {};
Object.defineProperty(todos, 'foo', {
    value : observable,
    configurable: true
});

const proxy = target.getProxy(todos);

const desc = Object.getOwnPropertyDescriptor(proxy, 'foo');
const { value } = desc;
value; Will be the raw observable object, expected to be a proxy
```

Added tests as part of a PR: https://github.com/salesforce/observable-membrane/pull/21

#### Expected Results
Should not be able to evade the membrane containment using getOwnPropertyDescriptor()
#### Actual Results
Able to get out of the membrane

#### Browsers Affected
all

#### Version
0.25.0

**Possible Solution**
```
getOwnPropertyDescriptor(shadowTarget: ReactiveMembraneShadowTarget, key: PropertyKey): PropertyDescriptor | undefined {
    const { originalTarget, membrane, valueObserved } = this;

    // keys looked up via hasOwnProperty need to be reactive
    if (!isUndefined(valueObserved)) {
        valueObserved(originalTarget, key);
    }

    let desc = getOwnPropertyDescriptor(originalTarget, key);
    if (isUndefined(desc)) {
        return desc;
    }
    // Fix
    if(configurable) {
        return wrapDescriptor(membrane, desc);
    }
    // endFix
    const shadowDescriptor = getOwnPropertyDescriptor(shadowTarget, key);
    if (!desc.configurable && !shadowDescriptor) {
        // If descriptor from original target is not configurable,
        // We must copy the wrapped descriptor over to the shadow target.
        // Otherwise, proxy will throw an invariant error.
        // This is our last chance to lock the value.
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/getOwnPropertyDescriptor#Invariants
        desc = wrapDescriptor(membrane, desc);
        ObjectDefineProperty(shadowTarget, key, desc);
    }
    return shadowDescriptor || desc;
}
```

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### PR DESCRIPTION
**Pull request by caridy**
This fixes issue #20 by allowing access to the wrapped values via accessors.

### CODE REVIEW

File: src/reactive-handler.ts [hunk 1]
```diff
@@ -28,13 +33,6 @@ function unwrapDescriptor(descriptor: PropertyDescriptor): PropertyDescriptor {
     return descriptor;
 }
 
-function wrapDescriptor(membrane: ReactiveMembrane, descriptor: PropertyDescriptor): PropertyDescriptor {
```
Comment (caridy) [inline src/reactive-handler.ts]: this is now lifted up to reactive-membrane so we can use it in multiple places.

File: src/reactive-handler.ts [hunk 2]
```diff
@@ -145,16 +143,19 @@ export class ReactiveProxyHandler {
             return desc;
         }
         const shadowDescriptor = getOwnPropertyDescriptor(shadowTarget, key);
-        if (!desc.configurable && !shadowDescriptor) {
+        if (!isUndefined(shadowDescriptor)) {
+            return shadowDescriptor;
```
Comment (caridy) [inline src/reactive-handler.ts]: being in the shadowTarget means that there is nothing else to do here, we can reliable use that one.

File: src/reactive-handler.ts [hunk 3]
```diff
@@ -145,16 +143,19 @@ export class ReactiveProxyHandler {
...
+        }
+        desc = wrapDescriptor(membrane, desc, getWrappedValue);
```
Comment (caridy) [inline src/reactive-handler.ts]: `wrapDescriptor` implements the full logic for set, get and value

File: src/reactive-membrane.ts [hunk 4]
```diff
@@ -68,6 +68,24 @@ const defaultValueMutated: ReactiveMembraneMutationCallback = (obj: any, key: Pr
...
+        descriptor.value = getValue(membrane, descriptor.value);
+    }
+    if (!isUndefined(get)) {
+        descriptor.get = function() {
+            return getValue(membrane, get.call(this));
+        };
+    }
+    if (!isUndefined(set)) {
+        descriptor.set = function(value) {
+            set.call(this, membrane.unwrapProxy(value));
```
Comment (caridy) [inline src/reactive-membrane.ts]: store the unwrapped value into the original target via the setter method.

File: src/reactive-membrane.ts [hunk 5]
```diff
@@ -68,6 +68,24 @@ const defaultValueMutated: ReactiveMembraneMutationCallback = (obj: any, key: Pr
...
 const defaultValueDistortion: ReactiveMembraneDistortionCallback = (value: any) => value;
 
+export function wrapDescriptor(membrane: ReactiveMembrane, descriptor: PropertyDescriptor, getValue: (membrane: ReactiveMembrane, originalValue: any) => any): PropertyDescriptor {
+    const { set, get } = descriptor;
+    if ('value' in descriptor) {
+        descriptor.value = getValue(membrane, descriptor.value);
+    }
+    if (!isUndefined(get)) {
+        descriptor.get = function() {
+            return getValue(membrane, get.call(this));
```
Comment (caridy) [inline src/reactive-membrane.ts]: getValue can do the wrapping when needed before returning the value to use-land

File: src/reactive-membrane.ts [hunk 6]
```diff
@@ -68,6 +68,24 @@ const defaultValueMutated: ReactiveMembraneMutationCallback = (obj: any, key: Pr
 };
 const defaultValueDistortion: ReactiveMembraneDistortionCallback = (value: any) => value;
 
+export function wrapDescriptor(membrane: ReactiveMembrane, descriptor: PropertyDescriptor, getValue: (membrane: ReactiveMembrane, originalValue: any) => any): PropertyDescriptor {
+    const { set, get } = descriptor;
+    if ('value' in descriptor) {
+        descriptor.value = getValue(membrane, descriptor.value);
+    }
+    if (!isUndefined(get)) {
```
Comment (caridy) [inline src/reactive-membrane.ts]: we were missing the logic for get and set when wrapping the descriptor.

File: src/read-only-handler.ts [hunk 7]
```diff
@@ -85,16 +83,20 @@ export class ReadOnlyHandler {
             return desc;
         }
         const shadowDescriptor = getOwnPropertyDescriptor(shadowTarget, key);
-        if (!desc.configurable && !shadowDescriptor) {
+        if (!isUndefined(shadowDescriptor)) {
+            return shadowDescriptor;
+        }
+        desc = wrapDescriptor(membrane, desc, getReadOnlyValue);
+        delete desc.set; // readOnly membrane does not allow setters
```
Comment (caridy) [inline src/read-only-handler.ts]: this logic is pretty much the same as the other file except for this line. in readonly membrane, we never expose a setter.

File: test/read-only-handler.spec.ts [hunk 8]
```diff
@@ -285,10 +285,10 @@ describe('ReadOnlyHandler', () => {
             const proxy = target.getReadOnlyProxy(todos);
             const desc = Object.getOwnPropertyDescriptor(proxy, 'entry');
             const { get } = desc;
-            expect(() => { 
+            expect(() => {
                 get().foo = '';
             }).toThrow();
```
Comment (pmdartus) [inline test/read-only-handler.spec.ts]: The `toThrow` should validate the error message to ensure it's the expected one.

File: test/read-only-handler.spec.ts [hunk 9]
```diff
@@ -304,7 +304,28 @@ describe('ReadOnlyHandler', () => {
             expect( () => {
                 value.foo = '';
             }).toThrow();
```
Comment (pmdartus) [inline test/read-only-handler.spec.ts]: The `toThrow` should validate the error message to ensure it's the expected one.

File: test/read-only-handler.spec.ts [hunk 10]
```diff
@@ -304,7 +304,28 @@ describe('ReadOnlyHandler', () => {
...
+                    value = v;
+                },
+                configurable: true
+            });
+            const proxy = target.getReadOnlyProxy(todos);
+            const desc = Object.getOwnPropertyDescriptor(proxy, 'entry');
+            const { set, get } = desc;
+            expect(() => {
+                set.call(proxy, 1);
+            }).toThrow();
```
Comment (pmdartus) [inline test/read-only-handler.spec.ts]: The `toThrow` should validate the error message to ensure it's the expected one.

File: src/reactive-membrane.ts [hunk 11]
```diff
@@ -68,6 +68,24 @@ const defaultValueMutated: ReactiveMembraneMutationCallback = (obj: any, key: Pr
...
+        descriptor.get = function() {
```
Comment (caridy) [inline src/reactive-membrane.ts]: TODO: this has the problem of the identity of the getter, asking for the descriptor twice for a configurable descriptor will give you different get functions, not a big deal, but solvable with a weakmap.

File: src/reactive-membrane.ts [hunk 12]
```diff
@@ -68,6 +68,24 @@ const defaultValueMutated: ReactiveMembraneMutationCallback = (obj: any, key: Pr
...
+            return getValue(membrane, get.call(this));
+        };
+    }
+    if (!isUndefined(set)) {
+        descriptor.set = function(value) {
```
Comment (caridy) [inline src/reactive-membrane.ts]: same as above, identity problems for configurable descriptors.

File: test/reactive-handler.spec.ts [hunk 13]
```diff
@@ -594,7 +594,7 @@ describe('ReactiveHandler', () => {
         expect(accessSpy).toHaveBeenLastCalledWith(obj.foo, 'bar');
     });
 
-    describe.skip('issue#20 - getOwnPropertyDescriptor', () => {
+    describe('issue#20 - getOwnPropertyDescriptor', () => {
```
Comment (pmdartus) [inline test/reactive-handler.spec.ts]: We should add `valueObserved` and `valueMutated` traps for all the tests to ensure that the membrane is catching those mutations properly.

File: src/reactive-membrane.ts [hunk 14]
```diff
@@ -68,6 +68,24 @@ const defaultValueMutated: ReactiveMembraneMutationCallback = (obj: any, key: Pr
 };
 const defaultValueDistortion: ReactiveMembraneDistortionCallback = (value: any) => value;
 
+export function wrapDescriptor(membrane: ReactiveMembrane, descriptor: PropertyDescriptor, getValue: (membrane: ReactiveMembrane, originalValue: any) => any): PropertyDescriptor {
+    const { set, get } = descriptor;
+    if ('value' in descriptor) {
```
Comment (pmdartus) [inline src/reactive-membrane.ts]: Can we use `descriptor.hasOwnProperty('value')` otherwise, can you add a component explaining why?

File: src/reactive-membrane.ts (hunk 6 above)
Comment (pmdartus) [inline src/reactive-membrane.ts]: `value` mutually exclusive with `get` and `set`. So we can create 2 branches, so you don't need to run the `get` and `set` branch if `value` is present.

```js
if (descriptor.hasOwnProperty('value')) {
	// ...
} else {
	if (!isUndefined(get)) {
		//...
	}
	if (!isUndefined(set)) {
		//...
	}
}
```

File: src/reactive-membrane.ts (hunk 5 above)
Comment (pmdartus) [reply src/reactive-membrane.ts]: Can you add a comment here? I had a hard time to understand why get and set are not symmetrical here.

File: src/read-only-handler.ts (hunk 7 above)
Comment (pmdartus) [inline src/read-only-handler.ts]: Performance wise, deleting the `set` key in the descriptor change the hidden class of the object, which is not perfect. What about adding a setter that throws a generic error?

File: src/reactive-handler.ts (hunk 2 above)
Comment (pmdartus) [reply src/reactive-handler.ts]: I don't understand this comment.

File: src/read-only-handler.ts (hunk 7 above)
Comment (caridy) [reply src/read-only-handler.ts]: not a big deal since descriptor objects are created every time by the engine.

File: src/reactive-handler.ts (hunk 2 above)
Comment (caridy) [reply src/reactive-handler.ts]: the `shadowTarget` is use to preserve the object invariants when the originalTarget has a non-configurable descriptor. In this condition, we check if we already have the descriptor fro the current key, and if we do, that's what we should return.

File: src/reactive-membrane.ts (hunk 11 above)
Comment (caridy) [reply src/reactive-membrane.ts]: We will track this in another issue after discussing it with @pmdartus .

File: test/reactive-handler.spec.ts (hunk 13 above)
Comment (caridy) [reply test/reactive-handler.spec.ts]: This is actually very interesting. `valueObserved` is marked when the descriptor is accessed, and `valueMutated` can't really be used effectively.
