### PR TITLE
fix: Add global this value lookup to enable node support

### LINKED ISSUE #29: Node support?
### Description

When loading this library in node, it throws an error:
```
/home/nicolo/Documenti/dev/babel/babel/packages/babel-traverse/node_modules/observable-membrane/dist/commonjs/observable-membrane.js:349
    const devWindow = window;
                      ^

ReferenceError: window is not defined
    at init (/home/nicolo/Documenti/dev/babel/babel/packages/babel-traverse/node_modules/observable-membrane/dist/commonjs/observable-membrane.js:349:23)
    at Object.<anonymous> (/home/nicolo/Documenti/dev/babel/babel/packages/babel-traverse/node_modules/observable-membrane/dist/commonjs/observable-membrane.js:356:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at _observableMembrane (/home/nicolo/Documenti/dev/babel/babel/packages/babel-traverse/lib/ast-membrane.js:9:39)
```

I can work it around by setting `NODE_ENV=production` so that that file isn't loaded, but I don't think that it should be a requirement.

#### Browsers Affected
node

#### Version
Node: 11
observable-membrane: 0.26.0

**Possible Solution**

Maybe check `typeof window !== undefined` at
https://github.com/salesforce/observable-membrane/blob/2764bb3154899f2323fc2a33b4028362bd4f2fd1/src/reactive-membrane.ts#L15
?

### PR DESCRIPTION
**Pull request by pmdartus**
Add global object lookup to not only rely on the `window` object but also `global` (node) and `self` (web worker).

Fix #29

### CODE REVIEW

File: src/reactive-dev-formatter.ts [hunk 1]
```diff
@@ -67,18 +63,32 @@ const formatter: DevToolFormatter = {
     }
 };
 
+// Inspired from paulmillr/es6-shim
+// https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js#L176-L185
+function getGlobal(): any {
```
Comment (caridy) [inline src/reactive-dev-formatter.ts]: I'm fine with this! Maybe it is also time to start doing `globalThis` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) as part of this condition.
